// <auto-generated />
public partial class ModificarProducto
{
    protected global::System.Web.UI.WebControls.TextBox txtId;
    protected global::System.Web.UI.WebControls.TextBox txtNombre;
    protected global::System.Web.UI.WebControls.TextBox txtPrecio;
    protected global::System.Web.UI.WebControls.DropDownList ddlCategorias;
    protected global::System.Web.UI.WebControls.Panel pnlEdicion;
    protected global::System.Web.UI.WebControls.Label lblMensaje;
    protected global::System.Web.UI.WebControls.SqlDataSource dsProducto;
}
